### PR TITLE
8 features to delete product by

### LINKED ISSUE #8: Features to delete product by id

### PR DESCRIPTION
**Pull request by hereisbicky**
- [x] product delete by id

### CODE REVIEW

**Comment by hereisbicky** [comment]
product delete by id

**Review by smruti-banty — CHANGES_REQUESTED** [review]
Change exception type and pull latest code before push

**Comment by hereisbicky** [comment]
product delete by id

**Review by smruti-banty — APPROVED** [review]
LGTM.

**Pull request merged**
